plugins:
  llm:
    enabled: true
    provider: ollama #openai  # openai or ollama
    openai:
      model: gpt-4o-mini
      maxTokens: 300
      temperature: 0.7
    ollama:
      model: gpt-oss:120b
      baseUrl: "http://localhost:11434"
      maxTokens: 300
      temperature: 0.7

  weather:
    enabled: true
    provider: open-meteo
    locations:
      - name: "東京"
        latitude: 35.6762
        longitude: 139.6503
      - name: "大阪"
        latitude: 34.6937
        longitude: 135.5023
    defaultLocation: "東京"

  calendar:
    enabled: true
    maxResults: 5

  time:
    enabled: true
    timezone: "Asia/Tokyo"

  reminder:
    enabled: true
    pollingInterval: 30  # seconds
    reminders:
      - minutes: 10
        urgent: false
      - minutes: 5
        urgent: true

  tts:
    enabled: true
    provider: voicevox #openai  # openai or voicevox
    openai:
      voice: shimmer  # alloy, echo, fable, onyx, nova, shimmer
      model: tts-1    # tts-1 or tts-1-hd
      speed: 0.95
    voicevox:
      speaker: 2 #23 #3      # 3 = ずんだもん (ノーマル)
      baseUrl: "http://localhost:50021"
